### ISSUE TITLE
Track recording starts too easily

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#104]
Track recording starts with a short touch on the Tracks icon - That can happen accidentally, and as recording is battery intensive, that is too easy. Better would be, in my opinion, to require a long touch for recording, and a short touch for tracks list. That would be more consistent with the places feature too, wouldn't it?

**Comment by hungerburg** [comment]
In the mean time, my morning alarm once failed on me, because Trekarta sucked dry all the battery busily recording standstill while idling on the desk - In the end, the front page trekarta.info need no rewrite neither :)

**Comment by andreynovikov** [comment]
May be it's a good idea to warn user on low battery.

**Comment by hungerburg** [comment]
Andrey, That would not have helped me then, because I was asleep.

**Comment by hungerburg** [comment]
PS: I think, a Low-Bat warning is up to the OS. Still, apps should behave in a way to make it not too easy to get there by accident. A long press to start recording goes that way and fits good with the places button behaviour too.
