### ISSUE TITLE
Download of maps not working

### ISSUE THREAD

**Issue by tigexplorer** [andreynovikov/trekarta#107]
Hi,

I've installed trekarta via F-Droid on Android 9.

Even I tab for downloading the world map, it dosn't downloade.
Also no map can be downloaded via *Manage maps*. It shows `n downloading` but nothing happens.

What can I do?

**Comment by RahiAkherajot** [comment]
I think your download manager is not poweeful
there should be an option to download these maps from an external (download manager) app

**Comment by tigexplorer** [comment]
Ah, I found it: Blockada has blocked download.
https://blokada.org/
