### ISSUE TITLE
GPX open from Files App

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#114]
There was an issue about something similar, maybe it got closed. With android 9, from Downloads app, I can select Trekarta on GPX files, but not with the Files app, that supersedes that.

Probably a look at https://github.com/MarcusWolschon/osmeditor4android/blob/241fddff5894052b723e2d8d78e7fa465166e405/src/main/AndroidManifest.xml#L66 might help (there is an extra android.intent.category.BROWSABLE, could that be all? At least vespucci as of very recently is available, but I did not find anything in the changelog.)

**Comment by hungerburg** [comment]
Recently, f-droid pushed an update, 2020-04; still no GPX handler, Vespucci the same too - I realised though, that when I save a GPX into `Internal Memory/Android/data/mobi.maptrek/files/data` it will show in Trekarta.

**Comment by hungerburg** [comment]
Some interesting news: in the Files app, marking a GPX and then hitting the "share" button will offer Trekarta-Import as a target to send the file to!

This will then copy the file to above location and make the trace show in Trekarta. Looks like "preview" or "open" need a different handler. For me, the "share" is good enough. It was not immediately obvious though.

**Comment by andreynovikov** [comment]
Please install https://f-droid.org/en/packages/de.k3b.android.intentintercept/ and run it. Then open GPX file from Files app, select Intercept the Intent (Just once) and copy what it shows.

**Comment by hungerburg** [comment]
Hmm, looks to me like an upstream (android) bug: from the Files app, some .gpx "cannot be previewed" or "none of your apps can open this", some (few!) open in Vespucci and only this is ever shown when I do "open with". Intent Intercept never gets trapped. All I can trap is "send to", see below:

intent:#Intent;action=android.intent.action.SEND;type=*/*;launchFlags=0xb080000;package=de.k3b.android.intentintercept;end ACTION: android.intent.action.SEND
MIME: */*
URI: intent:#Intent;action=android.intent.action.SEND;type=*/*;launchFlags=0xb080000;package=de.k3b.android.intentintercept;end
FLAGS:
FLAG_RECEIVER_REGISTERED_ONLY_BEFORE_BOOT
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP
FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET
EXTRAS:
1 Typ: android.net.Uri$HierarchicalUri
Key: android.intent.extra.STREAM
Wert: content://com.google.android.apps.nbu.files.provider/2/5487 AUFRUFBARE ACTIVITIES
keine

**Comment by hungerburg** [comment]
Having f-droid open, received an update for Vespucci, installed that, and now **no** app can open gpx from the "Files" app, that superseded the "Downloads" app with the 9 upgrade. No intent gets fired at all  (As seen from grepping for "ActivityManager:" in adb -d logcat) - pretty sure, that is a bug in the stock android, or is it google? app.

I installed "Material Files" from f-droid, and voilà, Trekarta properly gets suggested. Its is also a much cleaner filemanger, BTW ;) Below intent intercepted coming from material filemanager:

```
intent://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FThaur-Koanzensteig.gpx#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end ACTION: android.intent.action.VIEW
DATA: content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FThaur-Koanzensteig.gpx
MIME: application/octet-stream
URI: intent://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FThaur-Koanzensteig.gpx#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end
FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP AUFRUFBARE ACTIVITIES
Vespucci (de.blau.android - de.blau.android.Main)
Trekarta import (mobi.maptrek - mobi.maptrek.DataImportActivity)
```

**Comment by andreynovikov** [comment]
I've recently switched to Samsung and its stock file manager behaves the same way.

**Comment by pjones** [comment]
I just bought Trekarta and it took me quite a bit of digging around to figure out how to import data.  This issue makes it much harder to figure out.  Here are a couple of things I noticed:

  * The Samsung "My Files" app says there is no application that can open a GPX file and offers to open the Play store to find one.  This happens if the `*.gpx` file is on the internal storage or an external SD card.

  * The "FX" manager also says no application can open files of type `application/gpx+xm` if the file is on the external SD card.  If the file is on the internal storage I get a different error.  I've attached screenshots.

  * The "File Manager" application on f-droid works just fine.  It looks like it copies the file somewhere first then offers to open Trekarta.

It would be nice if the application mentioned that you need to share GPX files from a file manger to get them into Trekarta.  It would be even better if Trekarta could import them directly.

Finally, thank you very much for this application, and for releasing it as FOSS.  I no longer have to use a terrible handheld GPS.

![Screenshot_20200907-134028_FX](https://user-images.githubusercontent.com/3737/92644273-f275a080-f297-11ea-8aa3-a31eea70f0ff.jpg)
![Screenshot_20200907-134056_FX](https://user-images.githubusercontent.com/3737/92644293-f99cae80-f297-11ea-980d-16995606e5c8.jpg)

**Comment by hungerburg** [comment]
The recent changes did not help with the "Files Go" app, they seem to have their own mime matcher somewhere, that pre-empts the intent-mechanism. Perhaps google did "innovate" and forgot about GPX, as they have their own KML already.

PS: Clicking some.kml triggers an intent and "Trekarta Import" gets suggested:

```
intent://com.google.android.apps.nbu.files.provider/2/6786#Intent;scheme=content;type=application/vnd.google-earth.kml%2Bxml;launchFlags=0x3000000;package=de.k3b.android.intentintercept;end

ACTION: android.intent.action.VIEW
DATA: content://com.google.android.apps.nbu.files.provider/2/6786
MIME: application/vnd.google-earth.kml+xml
URI: intent://com.google.android.apps.nbu.files.provider/2/6786#Intent;scheme=content;type=application/vnd.google-earth.kml%2Bxml;launchFlags=0x3000000;package=de.k3b.android.intentintercept;end
FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP

AUFRUFBARE ACTIVITIES
keine 
```

Funnily, there is no path in there

**Comment by andreynovikov** [comment]
As Android recently becomes more and more conceptually broken I think I will add file import feature in application itself.

**Comment by hungerburg** [comment]
Probably of interest here - https://stackoverflow.com/questions/59968229/how-to-implement-a-custom-mime-type-for-action-open-document-intent - the accepted answer is not really promising - On my device (android 9), at least "share" lets me get a gpx into trekarta from the official file-manager.

**Comment by hungerburg** [comment]
Works for me :+1:
