### ISSUE TITLE
Download hint on every start

### ISSUE THREAD

**Issue by Hb-** [andreynovikov/trekarta#117]
On every start the app shows the message "For better experience, download detailed world map (57,67 MB. You can do it now or later at any time".

After downloading the world map and restarting the app this message appears again.

**Comment by andreynovikov** [comment]
It looks like something went completely wrong. Please reinstall the application (keeping any data safe if you have already collected any).

**Comment by Hb-** [comment]
A slow SD memory card configured as part of the internal memory caused this problem. After configuring the SD card as "External Memory" in Android the issue is gone.
