### ISSUE TITLE
Fewer house numbers displayed on Trekarta Lite than on OSM

### ISSUE THREAD

**Issue by ssb22** [andreynovikov/trekarta#121]
I'm trying to work out why this happens.  Compare these screenshots of Cambridge's Parkers Piece: the Trekarta Lite map has fewer house numbers on it than the openstreetmap.org map (Parkside's 13, 20, 22 and 23, and Park Cottage, are all labelled by openstreetmap.org but not by Trekarta)—

![Screenshot_20200608-220616_Trekarta Lite](https://user-images.githubusercontent.com/2261921/84081510-fe6e6f80-a9d5-11ea-89e5-bf25124c4a21.jpg) ![Screenshot_20200608-220630_Chrome](https://user-images.githubusercontent.com/2261921/84081523-04645080-a9d6-11ea-83c5-24d3396c588c.jpg)

Zooming in further does not make the missing numbers appear.

Trekarta's `app/src/main/java/mobi/maptrek/maps/maptrek/Index.java` shows the maps are coming from `https://trekarta.info/maps/index?...` and there doesn't seem to be any documentation saying how frequently this server is updated to latest OSM, so I guess one possible reason for having fewer house numbers is if the map data is old.  But on the Dorset map, at least one of the tracks I added to OSM myself in the past few months is already present on Trekarta, so it seems at least some of Trekarta's map data is fairly new.  And yet there seems to be no way to increase the level of house-number detail in Trekarta (none of the "Amenities" options affect it).  I'd like to at least know why some numbers are missing.  I can understand wanting fewer numbers to make the map less cluttered, but if I am trying to find a specific house, and I am sight-impaired so I cannot read door numbers from a distance, then I would like to see every number that we have data for, which is one of the reasons why I prefer OSM over Google Maps which has none.  So it would be nice to have an option to switch all the house numbers back on.  Thanks.

**Comment by andreynovikov** [comment]
This is because currently Trekarta does not process house numbers that are not linked to buildings.

As for map data, you can see its age on Map management screen.

**Comment by andreynovikov** [comment]
Fixed by 937f8a4f32587f9a30c7ec37a5475c522d19211f - will be available in next release.
