### ISSUE TITLE
Font size for localities

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#122]
Node tag "place=locality" is used do map features of different kind and importance. Sadly, OSM does not have a way to denote any variety. Trekarta shows them quite prominently. As much as I like the bold appearance, I'd suggest do make the font smaller, same as mountain peaks for example.

**Comment by hungerburg** [comment]
In the mean time I learned to love the big letters, maybe though they are really not adequate; probably a rendering like "place=suburb" might be more appropriate?

**Comment by hungerburg** [comment]
In the same manner, the names of wayside_shrines are much too big and appear too early, eg https://www.openstreetmap.org/node/1361377624 has a name when ruler shows 100m. Even with amenities/religious fully down/off.

**Comment by andreynovikov** [comment]
It sounds sensible to make locality font smaller, will do that.

As for wayside shrines, you can refer to map legend and see that I placed it in Attractions section. May be it's not 100% perfect but in my opinion they are more of historic/tourist place then religious. I would think about implementing multi-type amenities.

**Comment by hungerburg** [comment]
I have attractions greyed out, still wayside_shrines appear at zoom 200m (13?) (when nothing much else around) - memorials though comply - Perhaps, because it appears twice in this list?

https://github.com/andreynovikov/trekarta/blob/bd8ac66943d8953cd87840418b4a52c1e1b51ff9/app/src/main/java/mobi/maptrek/maps/maptrek/Tags.java#L1728

**Comment by andreynovikov** [comment]
It's not the source of the problem but thank you for noticing - it's weird!
