### ISSUE TITLE
Hiking style unpaved service highways

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#124]
In the neighbouring province, many tracks are tagged highway=service, surface=unpaved. As such they are hard to spot in hiking mode. It would be nice to render those just the same as tracks. I think that this may be of use all over the world?

"Hidden" track in below screenshot is https://www.openstreetmap.org/way/38753443

![Screenshot_20200618-202806](https://user-images.githubusercontent.com/586972/85058386-59585180-b1a2-11ea-9f5d-962d45d39894.png)

**Comment by andreynovikov** [comment]
This is a tagging problem. Service roads are small roads within compact territory for local access. I can not emphasize them otherwise all cities will become a mess. One thing I can do is make all minor roads equal in hiking mode.

**Comment by hungerburg** [comment]
Reading https://wiki.openstreetmap.org/wiki/Tag:highway=service and looking at the picture - the tagging conforms 100% :) Its true though, there the sub-tags make a difference, e.g. service=driveway is only of interest for parcel services.

**Comment by hungerburg** [comment]
Closing this issue, as this indeed only becomes visible in hiking mode, because in activity=none the paths become invisible too, so there will not be dangling paths then. Will prepare a patch for hiking mode that accounts for that.
