### ISSUE TITLE
Missing tile

### ISSUE THREAD

**Issue by svvac** [andreynovikov/trekarta#134]
I can't seem to be able to download a tile in the middle of France. Under `Manage maps` it appears unshaded, just like most ocean tiles, and cannot be selected for download.

Clearing storage, cache and reinstalling the app doesn't change this.

![image](https://user-images.githubusercontent.com/129217/102902427-46834a00-446f-11eb-8fb7-a1d888607854.png)

**Comment by Krophil** [comment]
I have the same problem (on Android 11)

**Comment by svvac** [comment]
Seems to have been fixed a little while ago.

**Comment by andreynovikov** [comment]
It looks like it was a map generation problem.
