### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [andreynovikov/trekarta#135]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
I confirm that at the moment there are no screenshots on [the application page in the F-Droid repository](https://f-droid.org/en/packages/mobi.maptrek/):

![Trekarta](https://user-images.githubusercontent.com/3509797/222977153-c069b9d3-633d-419c-9d2a-57ff7a8ce5f3.jpg)
