### ISSUE TITLE
Honor foot= flag in special cases

### ISSUE THREAD

**Issue by andreynovikov** [andreynovikov/trekarta#139]
https://www.openstreetmap.org/way/441558821 - should be rendered as not accessible for hiking
https://www.openstreetmap.org/way/368777970 - should be rendered as path

**Comment by hungerburg** [comment]
There is the less known route relation, route=foot, e.g. https://www.openstreetmap.org/relation/11648589
The wiki says, this is for shorter walks than route=hiking; For all that its worth, they are interchangeable. Worldwide, there are close to 50,000 acc. to taginfo.

**Comment by hungerburg** [comment]
As of now, it is still not fully working: There are paths with "access=private" that show available, and there are paths with "access=no;foot=yes" that do not show at all. I tried a lot, but I cannot get my head around the missing boolean operators in rendertheme. Perhaps it is easier, to unconditionally render without regard to access, and just change the backdrop (as a last step, or as a first step)?

**Comment by hungerburg** [comment]
Attached a patch, that tries to work it out with minimal intrusion; Looks ok-ish on the emulator. Will test it on the mobile now. Tracks still left to unmolested. Saves one level of intent in the style :)

[Hiking-Forbidden.txt](https://github.com/andreynovikov/trekarta/files/6108051/Hiking-Forbidden.txt)

Sample ways: https://www.openstreetmap.org/way/39496234 , https://www.openstreetmap.org/way/485746395

**Comment by andreynovikov** [comment]
Both render correctly for me. May be you have not applied all latest patches?

**Comment by hungerburg** [comment]
I made two screenshots, current master and my branch. I do not see the closed path in master (left).

![Screenshot_Hochnissl-Master](https://user-images.githubusercontent.com/586972/110528890-ea989b00-8118-11eb-9e3b-64e5f0cae088.png) ![Screenshot_Hochnissl-roverdub](https://user-images.githubusercontent.com/586972/110528902-ed938b80-8118-11eb-967c-dbc06b91a3df.png)

I will make line-caps not butt, that makes the overlapping segments too distinct. Should be decent, yet visible, so width=fix in hiking activity. Also shows enlarged ridge, that adds some noise to the area.

**Comment by andreynovikov** [comment]
It can be seen on left screenshot in fact. But I didn't emphasize it in hiking mode. Fixed it in https://github.com/andreynovikov/trekarta/commit/14e6d55395bb6d90dc75b9b0a7ced3ee97adc5ae

**Comment by hungerburg** [comment]
I wrote a comment there yesterday and sent a reworked suggestion, how to make them a bit less prominent, than they became with that change. Do they need a background line? Is it for the legend?

This also makes it apply to paths that have an access key only. As of now, these are missed by the rule.
