### ISSUE TITLE
Ridges and Aretes

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#141]
Trekarta has contours and hillshading, can the be lighter? Patch and screenshot below.

![Screenshot_RidgesAretes](https://user-images.githubusercontent.com/586972/110173872-91bac100-7dff-11eb-931c-ba20af3ea881.png)

[AretesRidges.txt](https://github.com/andreynovikov/trekarta/files/6093403/AretesRidges.txt)

Unfortunately, symbol-percent only seems to grow in steps

**Comment by andreynovikov** [comment]
Done in https://github.com/andreynovikov/trekarta/commit/a97a07a456affe17b7e081d0dfb263595359c199
