### ISSUE TITLE
Hiking Tunnels

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#143]
These are rare indeed, I found one, https://www.openstreetmap.org/way/39448447

Below a possible change in styling

``` patch
b/app/src/main/assets/styles/inc_highways.xml
@@ -46,8 +46,8 @@
                                         <line stipple="6" use="path" width="2.0" stipple-stroke="color:cycleway" />
                                     </m>
                                     <m cat="hiking">
-                                        <line cat="hiking" use="path" width="6.0" />
-                                        <line fix="true" stroke="color:land" width="5.6" />
+                                        <line stipple="12" stipple-stroke="color:transparent" use="pedestrian-tunnel"
+                                            fix="true" width="6.0" />
                                     </m>
                                     <m>
                                         <line stipple="6" use="path" width="2.0" />
```

**Comment by andreynovikov** [comment]
Do not see any problems with tunnels. They are correctly drawn in both modes.

**Comment by hungerburg** [comment]
Hello Andrey, Below two screenshots of what I see in hiking mode, can this be so different? - not perfect, but I can't do it better, eg. like motorway tunnels, that have a dashed outline… got so far from looking how you did with cycling tunnels, some lines below there… third shot from cycling, much nicer

![Screenshot_1615722428](https://user-images.githubusercontent.com/586972/111067338-1a9ec000-84c4-11eb-9c3b-0676ca308ccd.png) ![Screenshot_1615722620](https://user-images.githubusercontent.com/586972/111067339-1e324700-84c4-11eb-931c-04b21a827870.png) ![Screenshot_1615723452](https://user-images.githubusercontent.com/586972/111067751-e75d3080-84c5-11eb-974b-fe7a930aee9d.png)

**Comment by andreynovikov** [comment]
Updated
