### ISSUE TITLE
Allow only while using the app

### ISSUE THREAD

**Issue by mbenitob** [andreynovikov/trekarta#151]
Hi,
There is a problem that prevents Trekarta from recording tracks when the device has the screen off.
I think that the problem is that my Android device does not allow Trekarta to use GPS all the time but only while using the App.
See the pics better than thousand words.
Why the option to allow all the time is not available?
Thks!
![Screenshot_2021-04-14-21-17-15-612_com android settings](https://user-images.githubusercontent.com/17574244/114767179-9f9d2380-9d67-11eb-9763-fe28ef91ed40.jpg)
![Screenshot_2021-04-14-08-03-05-231_com google android permissioncontroller](https://user-images.githubusercontent.com/17574244/114767203-a4fa6e00-9d67-11eb-85d8-5bbce1ec1f88.jpg)

**Comment by andreynovikov** [comment]
"Allow all the time" is the new Android 11 feature. In fact this permission is required only for apps that use location in background invisibly - for example for geofencing or notifying on arriving at some place. Trekarta shows non removable notification when working in background, and it is not considered as "background work" by Android 11 (sorry for tautology). Furthermore this permission requires special approval from Google (with app audit procedure) which is hard to pass.

As for your problem - this is a known problem for this kind of devices. They try to save battery in such a way. For instance by default WhatsApp messages would not come until you open the app. To overcome this you have to set exceptions somewhere in device settings. I've made it once for my friend.

**Comment by mbenitob** [comment]
Many Thanks for your answer. 
Great work with your app!
Regards.
