### ISSUE TITLE
Optionally hide accessibility icons

### ISSUE THREAD

**Issue by haarp** [andreynovikov/trekarta#161]
Hi,

it's great to display accessibility next to amenities, something most map software pays no attention to. However, if you don't need this information, there is no way to disable it. It tends to crowd the display somewhat unnecessarily. Could be added to the features settings perhaps?

Thanks a lot! Looking forward to seeing this app further improved, it really is a joy to use. :)

**Comment by andreynovikov** [comment]
It can be disabled in settings.

**Comment by haarp** [comment]
Ah, there it is. I've been looking for it in amenities and features, where I would've expected them. Thanks!
