### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by qwerty287** [andreynovikov/trekarta#164]
First of all, thanks for this very nice maps application.
But one thing is missing: translations, the app is only available in English and Russian. To make it easy for other people to translate the app without having to create a pull request or to learn any XML styling formats, you could set up something like [Weblate](https://hosted.weblate.org), which [offers free hosting](https://hosted.weblate.org/hosting/) for open source projects. 
Thanks!

**Comment by nathanael-h** [comment]
Hello, I thank you for this great app that I use to track hicking. I am thinking about starting french translation. What would be the best way to contribute this ? PR with XML?

**Comment by andreynovikov** [comment]
Translation service is now awailable: https://github.com/andreynovikov/trekarta/wiki/Translation
