### ISSUE TITLE
OpenStreetMap is not properly attributed

### ISSUE THREAD

**Issue by matkoniecz** [andreynovikov/trekarta#178]
I managed to open app, download detailed map from OSM data and look around map - and OSM was not attributed.

Please, add attribution, required by its license https://www.openstreetmap.org/copyright

Typical location to provide attribution visible by all users is to put it into corner of the map

**Comment by hungerburg** [comment]
Openstreetmap contributors get attributed: There is a web-link, when the app starts or returns from background. Later it fades away. I accidentally clicked it much too often.

**Comment by matkoniecz** [comment]
OK, I will try look into it (I only quickly tested app - maybe I missed it? or maybe it was added later?)

**Comment by Animyos** [comment]
![Screenshot_20220715-214130_1](https://user-images.githubusercontent.com/82672160/179299555-b5297ed0-8da9-48dc-9ae6-c7695da17189.png)
It's a bit small and sometimes hard to see (depending on the background), but it's certainly there. The question is if a away-fading attribution is enough to fulfill the license or if it needs to be there all the time... But that's a question I'm not able nor willing to answer now, maybe someone other will.

**Comment by matkoniecz** [comment]
> away-fading attribution is enough to fulfill the license

yes, if it is visible to a typical user

I am not really convinced that it is visible or readable to a typical user (even if clickable by accident) but I will need to test it

**Comment by hungerburg** [comment]
It is impossible to not notice it - for regular users (I am.)
