### ISSUE TITLE
custom tile maps don't work anymore

### ISSUE THREAD

**Issue by SokoFromNZ** [andreynovikov/trekarta#191]
Hi Andrey,

I use Trakarta (not lite) and "basemap.at Online Maps for Trakarta" (https://play.google.com/store/apps/details?id=mobi.maptrek.maps.online.provider.basemapat) but I still get the "Your installed custom tile maps will appear here." message.

This worked fine in one of the older versions. I saw three options for basemap.at. I've even reinstalled everything but it still doesn't show up.

Thanks
Soko

PS: I can reproduce this bug on all of my 3 devices (Nokia 2.3, Oneplus 7 pro, Lenovo Tab P11 pro). All running Android 11.
PPS: I've tried all the plugins from https://play.google.com/store/apps/developer?id=Andrey+Novikov. None is working, not just the basemap.at...

**Comment by SokoFromNZ** [comment]
Awesome. When will you release an update on Google Play Store including this?

**Comment by andreynovikov** [comment]
Next week, I hope.

**Comment by SokoFromNZ** [comment]
Hi.
This worked great after you release in Dec.
But since the Icon/UI-Update-Version its broken again...
can this be?
thx

**Comment by andreynovikov** [comment]
Plugin API has changed. I will fix and release new basemap.at ASAP.

**Comment by andreynovikov** [comment]
Published updated version on Google Play

**Comment by SokoFromNZ** [comment]
Works now, awesome. thx.
