### ISSUE TITLE
Allow navigating through recorded tracks

### ISSUE THREAD

**Issue by umlaeute** [andreynovikov/trekarta#221]
in the view for a recorded track i can zoom and drag within the track's elevation profile and the speed profile.

i would like to propose two improvements:
- lock the view settings of the two profiles (so pinching in the elevation profile *also* zooms in the speed profile)
  (you might add a checkbox to enable/disable the locking if you want, but honestly i cannot really think of a need to be able to navigate the two profiles independently)
- also add a view on the actual map, so scrolling through a profile would also allow you to recap the track

honestly, i haven't actually needed one of the two proposals so far (though the independent navigation of elavation/speed did bother me a bit; now i'm mostly just *not* navigating them at all :-)), but i think together with #209 this would make a nice interface for being able interactively trimming tracks accurately.

**Comment by andreynovikov** [comment]
Added in 2024.02
