### ISSUE TITLE
"delete place" command disappear in new version

### ISSUE THREAD

**Issue by wu520609** [andreynovikov/trekarta#229]
Hello:

I have updated to version 2024.01. I found "delete place" command disappear in new version.
When I select some place items,There should a "delete place" command at upper right corner.
But right now,I can't find it.

**Comment by andreynovikov** [comment]
Do you mean multiple selection? It's there but it's white icon on white background, will fix that.

**Comment by andreynovikov** [comment]
Fixed in 2024.02
