### ISSUE TITLE
Empty map screen

### ISSUE THREAD

**Issue by maliayas** [andreynovikov/trekarta#230]
The app was working fine for years. However, several weeks ago for some reason all the maps disappeared. This is the screen I see:

![signal-2024-01-24-052326_002](https://github.com/andreynovikov/trekarta/assets/844008/d06c2c57-39f2-4afb-be0a-24e1e21651fc)

Any idea why this happens?

I was using v2022.05 at the time. I've updated to 2023.12 but it didn't fix it.

To give some clues:

- The issue started after a normal track recording. If I remember correctly, during that recording I used pause/resume feature offered by the app via the Android's top notification drawer. I didn't use pause/resume previously, so that feature may be to blame. To fix the issue, I tried removing some saved tracks but no luck, the bug remained.
- The screenshot above is not actually empty. Looking at the scale on top left, I guess it's just overly zoomed-out. Maybe a problematic coordinate point in one of the recorded tracks causes that?

**Comment by andreynovikov** [comment]
According to map scale bar zoom is out of range for some unknown reason. Try one of:

- triple tap on the map area
- select Manage maps from menu

If this will not help, I will add one more complicated option.

**Comment by maliayas** [comment]
Thanks for the help. Neither option fixed it. Map scale is still the same.

**Comment by andreynovikov** [comment]
Try this:

1. Download [Moscow 1852 custom map](https://trekarta.info/Moscow%201852.mbtiles) on device
2. Import it with Trekarta
3. Restart Trekarta (swipe it from recent apps and start again), otherwise it will not show new map
4. Touch Maps icon, imported map should be there, similar to: ![](https://trekarta.info/images/maps.png)
5. Touch that map to activate it, position and zoom should be changed to show this map

**Comment by maliayas** [comment]
![[](url)](url)

**Comment by andreynovikov** [comment]
This is absolutely weird. All these actions forcibly set map scale. I will investigate this issue. Meanwhile the only option left is to reinstall the app. But you have to **pay attention** that during reinstall all data created in app (points, tracks) **will be lost**. You have to **carefully backup** that data from `Android/data/mobi.maptrek/files` **by yourself**.

**Comment by andreynovikov** [comment]
Thank you a lot for issue report. I have finally magically found the source of a problem while testing very different part of application. The problem was with a track with only one point, which almost never happens.

**Comment by maliayas** [comment]
Wow, that's very good news and interesting at the same time! Looking forward to the next version. Thanks.

**Comment by maliayas** [comment]
I've installed the new version and news are bad :) The issue still exists and all the manual fix suggestions above still produces no fix.

I guess I'll reinstall the app. Just replied here so that you'd be aware that a nasty bug still hides somewhere in the code.

Thanks.

**Comment by andreynovikov** [comment]
Unfortunately, it can not fix consequences, only prevent it from happening. But now you can go to Advanced settings and reset map state. It will fix it.

**Comment by maliayas** [comment]
Ahh, finally my Trekarta is back. Thanks very much. I'm glad that this mystery is solved out.
