### ISSUE TITLE
Current track is not drawn after un-pause

### ISSUE THREAD

**Issue by SokoFromNZ** [andreynovikov/trekarta#275]
Hi,

I thought I've read about this issue somewhere but couldn't find it here. Maybe it was just in the release notes? Or is it related to #188 ?

Anyhow...

I ride my bike to the fitness center on a weekly basis and pause the recording during my workout. After unpausing the red line is not drawn anymore on my way home.
After I stop/save the recording the full line is shown. So I think its just a drawing issue, not a recording issue.

I you cannot reproduce it let me know how I can help.

Soko

**Comment by andreynovikov** [comment]
I can not reproduce it neither. I pause recording, close the app, start the app, unpause recording and track continues to draw.

**Comment by SokoFromNZ** [comment]
Hmm... thats weird. I have it 100% the time.
I ride my bike for ~1h.
Then I press pause (at the lock screen via the foreground service notification) and do my other stuff for ~0.5h.
Then I unlock the phone and open/start Trekarta. The GPS icon rotates until it has GPS lock again. Then I ride home.
=> no lines.
When I'm home I save the track: The line appears...

hhmm...while writing the above... does opening Trekarta automatically unpause the recording? At least thats what I thought. Or do I have to unpause it manually?
If I have to do it manually: Why is the ride home recorded correctly at the end when I save? Why isn't it a straight line between the pause-location and my home-location?
