### ISSUE TITLE
F-droid

### ISSUE THREAD

**Issue by ramack** [andreynovikov/trekarta#44]
Hello,

is there any chance to get this app into f-droid? I'd like to give it a try but building it myself is effort and also seems to not work (#18).
Additionally I'd like to ask about a schedule for the first release...

Regards,
Rapha

**Comment by ramack** [comment]
I see activity, good! So let me push this question again: are there plans for or problems with f-droid? what is the overall status and roadmap?

I can also try to support for example with the f-droid things or some beta testing but only if the project members still have interest in this project and some release milestone is somewhat close, otherwise is doesn't seem to make much sense.

**Comment by andreynovikov** [comment]
I am not against publishing free version on F-Droid but it looks like not easy process.

**Comment by ramack** [comment]
Why? Do you have much non-free dependencies? Your code is GPL-v3 licensed, so you anyhow link only "free as in free software" libraries, so it should not be a big deal to push it to f-droid. The only thing is, that they do not want "beta" apps, so you should at least have a version that is somehow useful and to the extend stable, that you consider it possible for "the world to use it".

**Comment by andreynovikov** [comment]
No, I mean that the publishing procedure is complex. It is not just uploading the distribution file.

**Comment by ramack** [comment]
If this is the problem I could offer some initial help. Afterwards it is even simpler as you just have to tag a new version in git and it will automatically be on fdroid a few days after.

**Comment by Poussinou** [comment]
A `Request For Packaging` is now open [here](https://gitlab.com/fdroid/rfp/issues/517).

You can have a look at the process to add an app, it will help the app to reach the official repo faster.

**Comment by hotlittlewhitedog** [comment]
:fire: "I am not against publishing free version on F-Droid but it looks like not easy process."   
We already changed a lot of things.  
Think to use Auto-update mode (see wiki) with tag names for further updates.

**Comment by licaon-kter** [comment]
FYI this was merged in F-Droid, so other issues not withstanding, it will be in the next index update.

**Comment by licaon-kter** [comment]
@andreynovikov I'd like to make some things clearer.

So, when the app downloads the maps, where are those hosted?

Where do they come from?

What license do they exist under?

Are they available to everyone or just for the app users?

**Comment by ramack** [comment]
Thanks for developing the great app and making it available also for us (the strange f-droid only guys)

**Comment by licaon-kter** [comment]
@andreynovikov Hope you find time to answer my questions above. (or point me where in the docs you've already clarified it, if I missed it)

Thanks

Ref: https://gitlab.com/fdroid/fdroiddata/commit/c705a4d98f4c1da7b6da03e89df4f4313f1364a5

**Comment by andreynovikov** [comment]
> So, when the app downloads the maps, where are those hosted?

On my personal server.

> Where do they come from?

Don't really understand the question. Can this help? https://andreynovikov.info/trekarta-maps-native.html

> What license do they exist under?

It shows licence on start and can be also viewed in "About":

- Map data is ©OpenStreetMap contributors.
- Made with free vector map data from OpenStreetMapData and Natural Earth.
- Contour lines courtesy of OpenDEM.
- Hillshades courtesy of OpenSnowMap.org

> Are they available to everyone or just for the app users?

They can be downloaded by anyone but it's of little use as they have propriatory format (see link above).

**Comment by licaon-kter** [comment]
Thanks. This can be closed then.

**Comment by RicozOSM** [comment]
curious regarding the map data format: how does this compare size-wise with eg OpenAndroMaps or OsmAnd vector maps?
