### ISSUE TITLE
Clone maptrek branch of vtm repository?

### ISSUE THREAD

**Issue by carlos-mg89** [andreynovikov/trekarta#50]
Hi,

I haven't found the maptrek branch in the vtm repository (actually, in the Github page there's only the master branch).

Besides that, I can't really manage to run the tasks you mentioned in the readme (possibly due to the previous issue I had with the maptrek branch) vtm:vtm install, vtm:vtm-android install and vtm:vtm-http install.

Any ideas? I have been a little bit out of Android development for a few years, so some concepts are quite recent for me.

**Comment by andreynovikov** [comment]
For VTM I mean my clone of VTM: https://github.com/andreynovikov/vtm/tree/maptrek

I use AndroidStudio, there on the right edge of the window you can open Gradle tasks list. Search for specified task and double click it, the task will execute. It can also be run from the command line but I have never tried that.
