### ISSUE TITLE
Sort search results and waypoints by distance

### ISSUE THREAD

**Issue by alex3s** [andreynovikov/trekarta#51]
Hi, Trekarta is a great app! Thanks!
The only way I came up to (roughly but quickly) sort search results and waypoint list by distance is this:
Do you have any better way in mind? Cheers!
(edit: improved sorting accuracy)
```
        double cos2 = Math.cos(Math.toRadians(mCoordinates.getLatitude()));
        cos2=cos2*cos2;
        final String orderby = " ORDER BY ((lat-(" + Double.toString(mCoordinates.getLatitude()) + "))*(lat-(" + Double.toString(mCoordinates.getLatitude()) + "))+("+Double.toString(cos2)+")*(lon-("+Double.toString(mCoordinates.getLongitude())+ "))*(lon-("+Double.toString(mCoordinates.getLongitude())+ "))) asc ";

        final String sql = "SELECT DISTINCT features.id AS _id, kind, lat, lon, names.name AS name FROM names_fts" +
                " INNER JOIN names ON (names_fts.docid = names.ref)" +
                " INNER JOIN feature_names ON (names.ref = feature_names.name)" +
                " INNER JOIN features ON (feature_names.id = features.id)" +
                " WHERE names_fts MATCH ? AND (lat != 0 OR lon != 0)" + kindFilter +
                orderby +
                " LIMIT 100";

```
Snippet added to TextSearchFragment.java

```
    private int mLatE6;
    private int mLonE6;

    public void setOrigin (double latitude, double longitude)
    {
        mLatE6=(int)(latitude*1000000);
        mLonE6=(int)(longitude*1000000);
    }

        if (mLatE6!=0 || mLonE6!=0) {
            double cos2 = Math.cos(Math.toRadians(0.000001*(double)mLatE6));
            cos2=cos2*cos2;
            final String orderby = "((latitude-(" + Integer.toString(mLatE6) + "))*(latitude-(" + Integer.toString(mLatE6) + "))+("+Double.toString(cos2)+")*(longitude-("+Integer.toString(mLonE6)+ "))*(longitude-("+Integer.toString(mLonE6)+ "))) asc";
            return mDatabase.query(WaypointDbHelper.TABLE_NAME, mAllColumns, null, null, null, null, orderby, " 100 ");
        }
```
Snippet added to WaypointDbDataSource.java

And in MainActivity.java :
```
    private void onPlacesClicked() {
     mWaypointDbDataSource.setOrigin(mMap.getMapPosition().getLatitude(),mMap.getMapPosition().getLongitude());
...
```

**Comment by andreynovikov** [comment]
I will try this, thanks!

**Comment by andreynovikov** [comment]
I have implemented a little bit another logic:
- amenities search result is always sorted by distance
- places are sorted by distance only if location is currently enabled

**Comment by andreynovikov** [comment]
Have published 2019.beta64 with this enhancement.

**Comment by alex3s** [comment]
Really great! Trekarta is a great software already. 
Using it I've encountered the following problem:
I search for the closest toilet or camping spot, etc On the map a toilet is displayed close to me when I zoom in there, but since it's outside of the view on my phone, I'm not aware of it's existence until I zoom in and look around. When I search on the list, only the named amenities are displayed. As far as I know, it's because the sql filter is using names of places. Toilet without a name will not appear. Can we improve it?

**Comment by andreynovikov** [comment]
@alex3s Yes, search is obviously searching by name. Toilets in most cases do not have names. I will think how to implement it (in terms of UI).

**Comment by andreynovikov** [comment]
@alex3s Do you know that you can configure the zoom level at which toilets and other hiking amenities will be shown?
