### ISSUE TITLE
Trekarta won't download any maps

### ISSUE THREAD

**Issue by matozoid** [andreynovikov/trekarta#53]
Hello! I installed Trekarta from the play store. When it starts to download the base map or any other map, it will show a download notification that disappears immediately. It shows a few more times (disappearing instantly) and then seems to give up. No data is downloaded, the app data usage is at 100-200k only.

**Comment by matozoid** [comment]
Today I tried the app again, and now it works.

I see a thumbs up from @eridrivic on my message, so I'm not sure if I should close it.

**Comment by andreynovikov** [comment]
Fixed
