### ISSUE TITLE
Render via ferrata's?

### ISSUE THREAD

**Issue by RicozOSM** [andreynovikov/trekarta#55]
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dvia_ferrata
https://wiki.openstreetmap.org/wiki/Key:via_ferrata_scale

**Comment by andreynovikov** [comment]
I already have them in map data, didn't have time to think of how to render them (visually). Any suggestions?

**Comment by andreynovikov** [comment]
I think this would be a good start: https://wiki.openstreetmap.org/wiki/Proposed_features/via_ferrata

**Comment by andreynovikov** [comment]
Rendered

**Comment by RicozOSM** [comment]
great thanks:)
