### ISSUE TITLE
links to outdated apks on the webpage 

### ISSUE THREAD

**Issue by mash-graz** [andreynovikov/trekarta#57]
the download links on the [trekarta webpage](https://maptrek.mobi/) are pointing to outdated (vers. 2017.11) apks. that's not an important issue for most users, because most of them will use googles playstore, but for google-service-free LinageOS and [/e/.foundation](https://e.foundation/)-users it's a little bit irritating. CI-generated apks in the github release section and accessibility via f-droid (#44) would be even a more pleasant solution.

**Comment by andreynovikov** [comment]
Fixed on website.
