### ISSUE TITLE
Support tile images from map plugins

### ISSUE THREAD

**Issue by alex3s** [andreynovikov/trekarta#59]
Andrey, Thanks for making Trekarta!
It would be really good to have the possibility to see a satellite map in addition to the normal map. 
Unfortunately downloading in advance a georeferenced images is not always handy.
Could we implement the map format borrowed from [QGroundControl](https://github.com/mavlink/qgroundcontrol/tree/master/android)
Why? Just as you mentioned about hillshades, travel time through bushed and wooded area is different, and sometimes these things can be seen only on satellite. 
QGroundControl uses already a sqlite database map format and there is GPL source available at the link above. What is your opinion about being able to use it's offline map format?

**Comment by andreynovikov** [comment]
The problem with satellite maps is that all known satellite image providers explicitly prohibit its use outside their domain. I've looked at QGroundControl code - all satellite imagery provides they are using do not allow such use. My another application (Androzic) was blocked by Google several years ago for that. That's why I'm very cautious to this nowadays.

Formally one could read QGroundControl map caches and shift this responsibility to them but it's like buying stolen things.

From technical point of view QGroundControl map caches are simple SQLite databases. Trekarta supports tile map provider plugins (https://github.com/andreynovikov/trekarta-online-maps). So it is very easy to write such plugin if you know Java language. And this solution seems much better then embedding support of propriatory format in Trekarta itself.

**Comment by alex3s** [comment]
That's a very reasonable explanation. Thank you for your insight, and for making Trekarta. Most people in my family like to use it from time to time for all kinds of outdoor related activities and I have a bunch of QGControl map cache files laying around, so, YES, I would like to develop (or someone else to develop) a map plugin reading the SQLite databases created by QGC. Please point me in the right direction, which plugin is the closest to what we want to achieve?

**Comment by andreynovikov** [comment]
Take any sub-project (they are combined in one AndroidStudio project, but you will need only one). Let's say it's "basemap.at".
1. Copy all its files in your project.
2. Replace all occurrences of substring "basemapat" with your selected name in all text files (java, xml, gradle).
3. All configuration is done in res/values/*.xml - leave only one map definition there (basemap.at exposes three).
4. Go to java source for ContentProvider. This is the place where tile should be extracted from SQLite database.
5. I don't know how you will find your file path, but then you open it as database with the following code: ```mDatabase = SQLiteDatabase.openDatabase(file.getAbsolutePath(), null, SQLiteDatabase.OPEN_READONLY)``` in ```onCreate()``` method.
6. QGControl uses [hash function](https://github.com/mavlink/qgroundcontrol/blob/ecdb5841406c975b3f75bddd16fd2e42bb025672/src/QtLocationPlugin/QGCMapEngine.cpp#L284) to encode z/x/y tile coordinates. You will have to re-implement it in Java. The only question there is what is ```UrlFactory::MapType```.
7. You will have to perform reverse engineering of database structure, most of the code can be found [here](https://github.com/mavlink/qgroundcontrol/blob/master/src/QtLocationPlugin/QGCTileCacheWorker.cpp). BTW, it [looks like](https://github.com/mavlink/qgroundcontrol/blob/9765125da5d65e3b11d1acc0d1f1e942bad63a76/src/QtLocationPlugin/QGCTileCacheWorker.cpp#L225) there can be more then one tile set in the database... When you will figure out correct SQL query to get the tile you will be ready to read it in your app.
8. Now go to ```query``` method and change it to extract tile from QGControl database. You can find example of reading tile from database here: [SQLiteTileDatabase.java#L62-L71](https://github.com/andreynovikov/trekarta/blob/41ec36d6b6bb966efec82f7d844ebc816ca74e90/app/src/main/java/org/oscim/tiling/source/sqlite/SQLiteTileDatabase.java#L62-L71).

_At this point I have figured out that I only planed to make it possible to pass ready to use tiles to Trekarta from plugin... But now it can pass only URLs. So I will implement this next month in one of the upcoming beta releases._

Fill free to ask any questions.

**Comment by alex3s** [comment]
Thank you Andrey for such a detailed instructions. So far I had problems with Gradle 2.1.2  (classpath 'com.android.tools.build:gradle:2.1.2') and upgrade to a newer gradle did not work with my Android plugin. 
Regarding` QGC: UrlFactory::MapType` seems to encode the information if map tile is Google, Bing, etc or an elevation tile. It stores them all in the same database, however elevation is not used to display a 3D map, but to calculate the UAV flight path around hills and valleys. I plan only to use the picture tiles from Bing maps.
Thanks for the tip about asqlitemanager. So far I use this: https://play.google.com/store/apps/details?id=com.lastempirestudio.sqliteprime which is also a nice app.

**Comment by andreynovikov** [comment]
I suggest you not clone existing project but create new empty object from scratch and copy only source files there. Then you will not have any compatibility problems as my project is pretty old.

**Comment by alex3s** [comment]
Thank you. Andrey, is the new Trekarta 2019 accepting image data from the plugins? Or is it only URLs accepted? Can you please create an empty plugin project so we can download it? Thanks.

**Comment by andreynovikov** [comment]
Sorry, worked on other issues. Will return to it shortly.

**Comment by andreynovikov** [comment]
Sorry that it took so long. Example source code can be found in https://github.com/andreynovikov/trekarta-online-maps/tree/master/worldmap
