### ISSUE TITLE
Viewing POI info

### ISSUE THREAD

**Issue by dimqua** [andreynovikov/trekarta#60]
Is it possible to get some information about POIs on the map? When I tap on them, nothing happens.

**Comment by andreynovikov** [comment]
I have it in my plans. Not in the next release but still on top of my todo list.

**Comment by andreynovikov** [comment]
- [ ] Add POI data in DB
- [ ] Extend amenity information panel
- [ ] Localize opening hours
- [ ] POI titles
- [ ] Handle DB updates

**Comment by andreynovikov** [comment]
![Screenshot_20191008-004407](https://user-images.githubusercontent.com/2943625/66351946-4cbf0080-e967-11e9-8a15-ca58cb4274f0.png)
