### ISSUE TITLE
Trekarta has extremly high battery use

### ISSUE THREAD

**Issue by paulle** [andreynovikov/trekarta#62]
Trekarta has extremly high battery use. Is this normal? Sony xperia xz2, android9.
![screenshot_20190131-170037](https://user-images.githubusercontent.com/4852079/52122670-040ab700-2624-11e9-949f-226497c5e0cf.png)

**Comment by andreynovikov** [comment]
Is it at normal operation or when loading and importing maps?

**Comment by paulle** [comment]
Its at normal operation.

Am 4. Februar 2019 19:05:05 MEZ schrieb Andrey Novikov <notifications@github.com>:
>Is it at normal operation or when loading and importing maps?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andreynovikov/trekarta/issues/62#issuecomment-460349902

-- 
K-9 Mail

**Comment by andreynovikov** [comment]
What exactly are you doing in application? Writing track? Navigating? Something else?

**Comment by paulle** [comment]
I was writing a track. And as far as I remember I did nothing special. 
In these days I have to stay at home, but in one of the next days, I can repeat what I did, if this will help you.

**Comment by paulle** [comment]
It seems the problem is solved.Why and how I don't know.
I deleted trekarta and installed otherwise (all via f-droid).
Later I wrote a track (about 40 minutes) and battery usage was 2%.
That's much better than before (16min 10%).
