### ISSUE TITLE
Menu for importing/exporting tracks

### ISSUE THREAD

**Issue by geronimoge** [andreynovikov/trekarta#66]
First of all thanks for the great app.

It would be fantastic if there would be a menu to import and export tracks (*.gpx, ...).
Being able to choose more than one file or perhaps whole directories would be perfect.

**Comment by LukeMarlin** [comment]
Seconding this, especially export in my case.

To get the GPX from a track, I had to export => signal to some guy and then download via signal app :(

I might have missed how to properly do it though!

**Comment by LukeMarlin** [comment]
I'm sorry for not being clear.
My need is to just export to phone storage, but since there is only the "share" option, my workaround is to share to some person so it sends it back to me, or mail myself, which isn't practical.

**Comment by andreynovikov** [comment]
Share options depend on what applications are installed on your phone. If you have some file management app it will let you save exported track in local file. I use Solid Explorer for file management but there are many other good applications.

**Comment by LukeMarlin** [comment]
Hm, I've tried two different from f-droid, on luck yet. But it makes sense to rely on the share instead of implementing a menu yourself, so you can close the case. I'll try to find an explorer that accepts shares on f-droid :)

**Comment by andreynovikov** [comment]
I've added explicit import option in the latest release.
