### ISSUE TITLE
Zooming changes location

### ISSUE THREAD

**Issue by alex3s** [andreynovikov/trekarta#69]
When zooming out using the on-screen buttons, the geographical location moves more than one screen to north west.
Conversely, when zooming in it moves to south east. Tested on Android 7.0.

**Comment by hungerburg** [comment]
Affects me too - I think this only happens, when there is a GPS lock on. Would you reopen?

**Comment by alex3s** [comment]
Do you have the latest version, marked January 2019?
Reopened just in case...

**Comment by hungerburg** [comment]
No :) I have version 2019.07 - I had 2019.01 - both behave the same - zooming, when a GPS position is available, shifts center of the map - this never happens, when no GPS position is used.

**Comment by hungerburg** [comment]
Finally came around to dig into this some more - I guess, this will be low hanging fruit! For reference - this only happens with a GPS position drawn outside of the view. Below two animations:

1. The GPS position is in view, it will remain on the same spot of the viewport
2. The GPS position is out of view, something complex happens ;)

       ![Zoom-OK](https://user-images.githubusercontent.com/586972/68996960-3af34600-08a1-11ea-8274-848ce93fc6f3.gif)                       ![Zoom-BUG](https://user-images.githubusercontent.com/586972/68996963-3f1f6380-08a1-11ea-9757-8bd33a074c35.gif)

Easy solution: if GPS position is not in viewport (i.e. blurred), use crosshair as centre for the zoom, just like if there was no GPS position at all.
