### ISSUE TITLE
displaying a track from an external kml file impossible?

### ISSUE THREAD

**Issue by legrostdg** [andreynovikov/trekarta#73]
I clicked on an external .kml file in Files, selected "Trekarta import", got a message "File is saved in application folder. Open Trekarta", but then I don't see the track I imported... When I click on the places icon, I don't see the external track, only the places I saved in the app, and a message "You can also import GPX and KML files.". Maybe it's me, but I don't understand how to display this kml file...

**Comment by hungerburg** [comment]
For me, GPX import does not work -- Downloads says: "File cannot be opened". When I try "Open with" Downloads says "No app can do this" -- Is Trekarta missing an entry in the OS mime.types table?

Happily, kml works for me; Maybe Trekarta does not automatically zoom to location?

**Comment by andreynovikov** [comment]
It should import both KML and GPX files and then display them in Places. If it is not please send me faulty track by email or attach it here (do not know if this will work).

**Comment by hungerburg** [comment]
Meanwhile my device got Android 9 and I also have installed Vespucci. The "Downloads" app now asks to choose between vespucci and Trekarta import; The "Files" app just fires up vespucci, when clicking a .gpx file. Download app also starts trekarta for .osm files (likely any other xml type?)

PS: Looking there - https://github.com/MarcusWolschon/osmeditor4android/blob/91e768df30b4fcaa400ff1667f8b7aef3f3ca1df/src/main/AndroidManifest.xml#L71 - the stance is written more compact, but should that matter?

**Comment by hungerburg** [comment]
Curiously, after renaming a .gpx via mounted USB, the Download app will ask, which app to use, but not after saving the file from ulogger.
