### ISSUE TITLE
enhancement: show elevation on certain nodes

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#75]
As multiline labels did land these days, it would be nice to have "ele" shown, e.g on "natural: peak", "natural: saddle" and "tourism: alpine_hut" -- should help tremendously calculating travel times.

**Comment by hungerburg** [comment]
Subject changed; Here in the Alps, lots of OSM guidepost nodes contain the full inscriptions - how about a popup on click/tap, that shows the "destination" tag, if specified. This sometimes has walking time, much better than routers can guess, esp. hiking routers.

**Comment by andreynovikov** [comment]
If data exists, elevation is shown for peak, saddle and mountain pass.

**Comment by hungerburg** [comment]
At a certain zoom-level ele is shown (100 m scale) - then the name of the summit is not shown - this only sometimes, when zooming out, never when zooming in - ele is written below the triangle symbol, while name is written above the symbol.

Note: this device has a very small screen, that might be an issue. Would be nice to have both when zoomed close, and for alpine_huts too. Closing, this sounds very complicated indeed!
