### ISSUE TITLE
GPS altitude

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#76]
Toying around in Trekarta, I find the reported elevation (in the extended info box left hand, and in recorded traks) consistently about 50 m too high. The "GPS-Test" app shows a much better match. This is with a Mediatek SOC and also with hillshades, just in case, that matters. Is that a bug?

**Comment by hungerburg** [comment]
I guess, I have found a bug. On a place with altitude known from local governmental GIS, Trekarta elevation is off by ~50m; EGM96 for this very location is ~48m.

To me, that looks like Trekarta does its own Geoid corrections on system readings, which already are corrected. If system values depend on OEM device configuration or android version, Geoid corrections should be configurable in preferences.

**Comment by andreynovikov** [comment]
Previously Android didn't apply geoid correction to altitude. Looks like modern versions do it. I will remove it from Trekarta.

**Comment by ulipo** [comment]
I resume this old issue as I noticed the same behaviour on v. 2024.03.22, see attached screenshot with split screen.
![Screenshot_2024-06-01-17-57-55-00_0692018f22614dd5789e3464f05cf011](https://github.com/andreynovikov/trekarta/assets/32038266/d65ec83e-a153-44ac-9910-535677067233)
