### ISSUE TITLE
Hiking Style Stipple

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#78]
The current rendering of hiking paths highlights the most inconvenient ways.

![Screenshot_20190923-135350](https://user-images.githubusercontent.com/586972/65423962-a8877680-de0a-11e9-8c1a-8710ae74261c.png)

- The brown line is a track: tracktype | grade2
- The blue line is a path: sac_scale | mountain_hiking; trail_visibility | good
- The short stipple red is: sac_scale | demanding_mountain_hiking; trail_visibility | bad
- The long stipple red is: sac_scale | demanding_mountain_hiking; trail_visibility | horrible

The effect of trail_visibility on stipple in Trekarta is reversed to what printed maps of the Alps usually do to indicate sac_scale: the longer the stipple, the easier the path, shortest (just dotted) are alpine routes with no visible path on the ground. Would you be willing to adopt this tradition in Trekarta, so that long stipple becomes good/intermediate and short stipple bad/horrible? I guess that should make a lot of people feel at home immediately.

Stipple also makes lines more prominent because of the white intermediate colour - can this be made transparent instead, or will they become too hard to spot then? Or could you draw stippled lines a little less wide or continous lines a little wider to counter that effect?

PS: Thank you for the good work!

**Comment by andreynovikov** [comment]
Yes, white is used to make them visible on various backgrounds, otherwise they will be hard to spot.
As for stripples - unfortunately I can not make white and color parts of different length, they have to be even. In other maps long colored stripples are combined with short transparent/white stripples. This makes them look like "visible". In my case I've used long transparent/white stripples to indicated poor visibility.

I will think about that.

**Comment by hungerburg** [comment]
Actually, I like the white background on stippled paths. The more there is white, the better it can be seen, most of the times. And a longer stipple makes more white.

To aid your deliberation, I patched styles/inc_hiking_routes.xml - bad becomes stipple 8; default becomes 24, intermediate remains 16, excellent gets width 6 to account for no-white.

![Screenshot_1569323219](https://user-images.githubusercontent.com/586972/65507036-45aae380-decd-11e9-9ba8-efeca032db62.png)

PS: maybe map data changed in between the screenshots, but I think it shows the difference quite nice
