### ISSUE TITLE
Build problem with Gradle

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#80]
In Studio Trekarta failes when updating Gradle - After some trickery, I now get this message:

> ERROR: It is not supported to define distributionSha256Sum in gradle-wrapper.properties.
> Please manually remove this property from all of included projects if applicable.
> For more details, see https://github.com/gradle/gradle/issues/9361.

Please remove offending line from source

**Comment by andreynovikov** [comment]
May be it depends on AndroidStudio version. This file is generated automatically by it.

**Comment by hungerburg** [comment]
I see, nevertheless, the checksum is out of date - https://gradle.org/release-checksums/ - the file wants 5.1 and has the checksum for 4.6 - nobody can compile Trekarta on their own as is, without manually changing the file to state 53b71812f18cdb2777e9f1b2a0f2038683907c90bdc406bc64d8b400e1fb2c3b as checksum there.

**Comment by andreynovikov** [comment]
BTW, standalone Gradle builds project perfectly, as indicated by [Travis](https://travis-ci.org/andreynovikov/trekarta). You can reference [configuration file](https://github.com/andreynovikov/trekarta/blob/master/.travis.yml) for details on build environment setup.
As for AndroidStudio - it's somewhat tricky, I always have issues each time I setup environment from scratch.
