### ISSUE TITLE
Elevation is off bij 100m

### ISSUE THREAD

**Issue by Woodhousemelena** [andreynovikov/trekarta#92]
Trekarta indicates that I am on 100m elevation. I assume that 0 is at sealevel, then my current elevation should be about 4 m. We can only wish to be at 100 m here in the Netherlands! ;-)

**Comment by Woodhousemelena** [comment]
I see now that there is a bug report in Issue #76

**Comment by andreynovikov** [comment]
Duplicate of #76

**Comment by hungerburg** [comment]
Pasting coordinates of Den Haag into this form https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html gives 100m correction against raw GPS readings.
