### ISSUE TITLE
packages generation

### ISSUE THREAD

**Issue by farfromrefug** [andreynovikov/trekarta#93]
I was wondering how you were generating your offline packages?
Right now i am using carto offline packages but they are really outdate.
I am thinking about generating my own.
Would you help?

Thanks

**Comment by andreynovikov** [comment]
What do you mean by "packages"?

**Comment by farfromrefug** [comment]
@andreynovikov sorry,  i mean the offline mtiles the app is downloading per region.

**Comment by andreynovikov** [comment]
They are generated by [special script](https://github.com/andreynovikov/mapcreator) and stored on server. You can look at `Makefile` or run `mapwrite.py --help` to figure out the start point. Default configuration requires some pre-processed data stored in PostGIS database. Its population is also defined in `Makefile`.

**Comment by farfromrefug** [comment]
@andreynovikov awesome will take a look at it!
Thanks
