### ISSUE TITLE
Closed/forbidden paths

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#97]
Tag "access=no/private" on paths does not render. On roads it does. Would be good though. Some are closed for a reason, eg. danger of falling rocks; and for quite some time too.

**Comment by andreynovikov** [comment]
Does it render on any other map? Need some ideas.

**Comment by hungerburg** [comment]
An example is https://www.openstreetmap.org/way/146344616 -  in mapnik it renders in shaded grey. The way itself must no be hidden, as it is widely known and it appears in many printed maps. One should be able to discriminate in a recent map though, that officially it is closed.
